#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NUM_REGISTERS 20

#define STATIC_ALLOC_START 4096
#define STATIC_ALLOC_END 4121

#define INTEGER_TYPE 0
#define BOOLEAN_TYPE 1
#define STRING_TYPE 2
#define NO_TYPE 3

#define YACC_DECL_INT 0
#define YACC_DECL_STR 1

enum nodeTypes {
    NODE_CONNECTOR = 1000,
    NODE_EMPTY,
    NODE_WRITE,
    NODE_READ,
    NODE_ASSIGN,
    NODE_ADD,
    NODE_SUB,
    NODE_DIV,
    NODE_MOD,
    NODE_MULT,
    NODE_ID,
    NODE_INT,
    NODE_STR_LTRL,
    NODE_EQ,
    NODE_NEQ,
    NODE_GTE,
    NODE_GT,
    NODE_LTE,
    NODE_LT,
    NODE_IF,
    NODE_IF_ELSE,
    NODE_WHILE,
    NODE_DOWHILE,
    NODE_REPEATUNTIL,
    NODE_BREAK,
    NODE_CONTINUE,
    NODE_ARR_IND,
};

enum errorCodes {
    SUCCESS = 999,
    E_OUTOFBOUNDS = -1000,

    E_REGFULL,
    E_INVALIDNODE,
    E_TYPEMISMATCH
};

#endif