#ifndef CONSTANTS_H
#define CONSTANTS_H

#define _NA_ -404

#define NUM_REGISTERS 20

#define STACK_START 4096
#define STACK_END 5119

#define HEAP_START 1024
#define HEAP_END 2047

enum dataTypes {
    INTEGER_TYPE = 0,
    BOOLEAN_TYPE,
    STRING_TYPE,
    INT_PTR_TYPE,
    STR_PTR_TYPE,
    PTR_TYPE,
    NO_TYPE,
};

#define YACC_DECL_INT 0
#define YACC_DECL_STR 1

#define LDECL_BINDING_START 1
#define PARAMS_BINDING_START -3

enum nodeTypes {
    NODE_CONNECTOR = 1000,
    NODE_EMPTY,
    NODE_WRITE,
    NODE_READ,
    NODE_ASSIGN,
    NODE_ADD,
    NODE_SUB,
    NODE_DIV,
    NODE_MOD,
    NODE_MULT,
    NODE_ID,
    NODE_INT,
    NODE_STR_LTRL,
    NODE_EQ,
    NODE_NEQ,
    NODE_GTE,
    NODE_GT,
    NODE_LTE,
    NODE_LT,
    NODE_IF,
    NODE_IF_ELSE,
    NODE_WHILE,
    NODE_DOWHILE,
    NODE_REPEATUNTIL,
    NODE_BREAK,
    NODE_CONTINUE,
    NODE_ARR_IND,
    NODE_ARR_IND_2D,
    NODE_ADDR_TO,
    NODE_DEREF,
    NODE_FN_CALL,
    NODE_RET,
    NODE_OR,
    NODE_AND,
    NODE_TUP_FIELD,
    NODE_ALLOC,
    NODE_FREE,
    NODE_INITLZE,
};

enum errorCodes {
    SUCCESS = 999,
    E_OUTOFBOUNDS = -1000,

    E_REGFULL,
    E_INVALIDNODE,
    E_TYPEMISMATCH
};

#endif